# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
project 'AppASW/AppASW.xcodeproj'
target 'AppASW' do
	pod "EVReflection", '~> 2.6'
    pod "Firebase/Database", '>=2.3.2'
    pod "AZDropdownMenu"
    pod "SideMenuController"
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppASW

  target 'AppASWTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppASWUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
